"""
Central configuration for MODULE 3 (LEGALMETRIX).

Every environment-dependent value used anywhere in Module 3 must be
read from this file, and nowhere else. This is the single place that
knows whether we are in MOCK_MODE and where Module 2 lives.
"""

import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def _get_bool(name: str, default: str) -> bool:
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


# ---------------------------------------------------------------
# Mock / live switch
# ---------------------------------------------------------------
MOCK_MODE = _get_bool("MOCK_MODE", "true")

# ---------------------------------------------------------------
# Module 2 integration
# ---------------------------------------------------------------
MODULE2_API_URL = os.getenv("MODULE2_API_URL", "http://localhost:8000").rstrip("/")
MODULE2_INSPECT_ENDPOINT = f"{MODULE2_API_URL}/analyze"
MODULE2_TIMEOUT_SECONDS = int(os.getenv("MODULE2_TIMEOUT_SECONDS", "10"))

# ---------------------------------------------------------------
# Storage
# ---------------------------------------------------------------
DB_PATH = os.getenv("DB_PATH", os.path.join(BASE_DIR, "database", "legalmetrix.db"))
REPORTS_DIR = os.getenv("REPORTS_DIR", os.path.join(BASE_DIR, "reports"))

os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
os.makedirs(REPORTS_DIR, exist_ok=True)

# ---------------------------------------------------------------
# App identity
# ---------------------------------------------------------------
APP_NAME = "ComplyAI"
APP_SUBTITLE = "Smart Product Verification"
PROJECT_CODE = "SIH26034"

DISCLAIMER_TITLE = "AI-Assisted Preliminary Screening"
DISCLAIMER_TEXT = (
    "This report is generated by an AI-assisted preliminary screening system. "
    "Final determination of legal compliance requires authorized human/regulatory review."
)

# ---------------------------------------------------------------
# Status constants (must exactly mirror what Module 2 returns)
# ---------------------------------------------------------------
STATUS_PASS = "PASS"
STATUS_REVIEW = "REVIEW"
STATUS_HIGH_PRIORITY = "HIGH PRIORITY"

STATUS_COLORS = {
    STATUS_PASS: "#1E8E5A",
    STATUS_REVIEW: "#C77700",
    STATUS_HIGH_PRIORITY: "#C0392B",
}

SEVERITY_COLORS = {
    "LOW": "#5B7DB1",
    "MEDIUM": "#C77700",
    "HIGH": "#C0392B",
    "CRITICAL": "#8E1B1B",
}
